name: Linter

on:
  pull_request:
    branches: [main]

jobs:
  linter:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npx eslint src
